import React from 'react';
import Head from 'next/head'

export default function About() {
    return (
        <div>
            <Head>
                <title>New title</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1> About </h1>
        </div>
    )
}
